import { sql } from 'drizzle-orm';
import { index, integer, jsonb, pgTable, text, timestamp, uuid } from 'drizzle-orm/pg-core';
import { authUsers } from './_auth.js';
import { callTranscripts } from './calls.js';
import { agentOpenItemKindEnum, agentOpenItemStatusEnum, claimStatusEnum } from './enums.js';
import { agents } from './identity.js';
import { wikiPages, wikiSections } from './wiki.js';

// Structured per-claim audit trail. v0.2 substrate.
//
// Claims are extracted from sources (today: call_transcripts; V1+: connectors,
// inbound docs, etc.) and optionally promoted into wiki_sections when they
// land as durable knowledge. The relationship is many-to-many in spirit but
// modeled as nullable FKs here — a claim can sit unattached if it's still
// being weighed, or attach to a section once it informs that section.
//
// Bi-temporal model (per DP-6, 2026-05-09):
// - `recorded_at`  — when WE learned the claim. Defaults to insert time.
// - `valid_from` / `valid_until` — when the claim IS or WAS true in the
//   real world. Both nullable: null `valid_from` = unknown start; null
//   `valid_until` = ongoing/still true.
// - `last_refreshed_at` — when the claim was most recently reconfirmed by
//   any source. Defaults to `recorded_at`; bumped by future ingestion when a
//   later source restates the claim. Used by stale-claim hygiene + dreaming's
//   recency weight.
//
// `confidence` is 0-100 (integer percent). Avoids floating-point comparison
// quirks; coarse enough that integer granularity isn't a real loss.
//
// `evidence` is a free-form JSONB array of source references — shape evolves
// with the prompt that produces it. Typical entries cite a transcript turn or
// URL plus a snippet. Schema-light intentionally; structure firms up as the
// fan-out prompt matures.
export const extractedClaims = pgTable(
  'extracted_claims',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    userId: uuid('user_id')
      .notNull()
      .references(() => authUsers.id, { onDelete: 'cascade' }),
    // The entity the claim is ABOUT. Required — every claim has a subject.
    subjectPageId: uuid('subject_page_id')
      .notNull()
      .references(() => wikiPages.id, { onDelete: 'cascade' }),
    // Optional: the section the claim was promoted into. NULL until promotion.
    wikiSectionId: uuid('wiki_section_id').references(() => wikiSections.id, {
      onDelete: 'set null',
    }),
    // Optional: the call this claim came from. NULL for non-call sources
    // (V1+ connectors, manual edits).
    callTranscriptId: uuid('call_transcript_id').references(() => callTranscripts.id, {
      onDelete: 'cascade',
    }),
    claimText: text('claim_text').notNull(),
    status: claimStatusEnum('status').notNull().default('supported'),
    // 0-100. Integer keeps comparisons exact; downstream reads as needed.
    confidence: integer('confidence'),
    evidence: jsonb('evidence').notNull().default(sql`'[]'::jsonb`),
    recordedAt: timestamp('recorded_at', { withTimezone: true }).notNull().defaultNow(),
    lastRefreshedAt: timestamp('last_refreshed_at', { withTimezone: true }).notNull().defaultNow(),
    validFrom: timestamp('valid_from', { withTimezone: true }),
    validUntil: timestamp('valid_until', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    userSubjectIdx: index('extracted_claims_user_subject_idx').on(t.userId, t.subjectPageId),
    sectionIdx: index('extracted_claims_section_idx').on(t.wikiSectionId),
    transcriptIdx: index('extracted_claims_transcript_idx').on(t.callTranscriptId),
    statusRefreshedIdx: index('extracted_claims_status_refreshed_idx').on(
      t.status,
      t.lastRefreshedAt,
    ),
  }),
);

// Per-persona queue of agent-initiated content delivered between or during
// calls. Two kinds (per DP-5, single-table model):
//
// - 'question'    — gap-filling. Generated by agent-scope ingestion when the
//                   persona notices missing knowledge. Terminates on
//                   'answered' (matched in a future transcript) or
//                   'dismissed' (user opted out) or 'expired' (timed out).
// - 'info_share'  — proactive enrichment. Generated when the persona spots
//                   relevant information to introduce next call. Terminates
//                   on 'surfaced' (delivered) or 'engaged' (user reacted) or
//                   'dismissed' / 'expired'.
//
// Read by the call-side prompt composer (v0.2 item #5) which weaves top-K
// items into the persona prompt. Lifecycle resolved by post-call fan-out
// (v0.2 item #6). Hygiene sweep expires stale items (v0.2 item #9).
export const agentOpenItems = pgTable(
  'agent_open_items',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    userId: uuid('user_id')
      .notNull()
      .references(() => authUsers.id, { onDelete: 'cascade' }),
    agentId: uuid('agent_id')
      .notNull()
      .references(() => agents.id, { onDelete: 'cascade' }),
    kind: agentOpenItemKindEnum('kind').notNull(),
    // Short topic/label — used for de-duplication, surfaceable in UI.
    topic: text('topic').notNull(),
    // The actual content. For 'question': the question text. For 'info_share':
    // the fact/observation to introduce. Persona prompt composer handles
    // natural-language framing — the body is the structured candidate.
    bodyText: text('body_text').notNull(),
    // 0-10. Higher surfaces sooner. Composer ranks by priority + recency.
    priority: integer('priority').notNull().default(5),
    status: agentOpenItemStatusEnum('status').notNull().default('pending'),
    // Provenance. The agent_scope ingestion run (or manual seed) that emitted
    // this item. Future hygiene + analytics rely on it.
    createdByTaskId: uuid('created_by_task_id'),
    // Cross-references to other open items (e.g. follow-up chain). JSONB so
    // shape can evolve.
    crossDomainLinks: jsonb('cross_domain_links').notNull().default(sql`'[]'::jsonb`),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    // Bumped on every write (status change, link update). Drives replication's
    // lastModifiedField — without it, server-side mutations (post-call
    // resolution, hygiene-sweep expiration) wouldn't reach the client. App
    // code is responsible for setting updated_at on update; Postgres won't
    // auto-bump.
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
    surfacedAt: timestamp('surfaced_at', { withTimezone: true }),
    resolvedAt: timestamp('resolved_at', { withTimezone: true }),
  },
  (t) => ({
    // Primary read path: composer pulls "pending items for this agent".
    agentStatusPriorityIdx: index('agent_open_items_agent_status_priority_idx').on(
      t.agentId,
      t.status,
      t.priority,
    ),
    // Hygiene sweep needs to find stale items.
    statusCreatedIdx: index('agent_open_items_status_created_idx').on(t.status, t.createdAt),
    userIdx: index('agent_open_items_user_idx').on(t.userId),
  }),
);
